### ISSUE TITLE
Does not work for long passwords/passphrases

### ISSUE THREAD

**Issue by darioackermann** [mkorz/b618reboot#9]
Thanks for the script. I am using it to motivate my B818-623 to reconnect to LTE when it occasionally decides to give up.
I have used a passphrase before (such as `Detection-Promenade9-Afford-Level`) and the script would fail in error and the router lock me out. Potentially there's an error in implementation, but in case anybody else should have this issue, changing to a shorter password without hyphens helped me.

**Comment by mkorz** [comment]
Thanks for the detailed report and most importantly for providing the sample password! This saved me a lot of time.

It turns out the router (for sure my B618s, but I suspect also other models) only uses first 32 characters of the password provided.

Looking at the login dialog, them limit is hard-coded:
```
<input type="password" autocomplete="off" class="input" id="password" maxlength="32" tabindex="2">
```

The sample password you provided is **33** characters long - when I removed the very last character, script worked properly.

As I am not sure if the newer models carry the same limit, I think I will just add the warning for passwords longer than 32 characters and will leave to the user to shorten the password in configuration if required.

Thanks again for reporting this!

**Comment by darioackermann** [comment]
Huawei had me in the first half, not gonna lie. I have never noticed that since I'm using a password manager... 🤭

I suppose this lies somewhere within the authentication protocol (or bare [poor] design choice), but we can't know how other models/versions handle this, so I think adding a notice is the way to go.

Thanks for digging into the rabbit hole!

**Comment by mkorz** [comment]
You are welcome, I am happy this was a quick one to fix. 

I have just pushed a branch with a warning message, I have also added information to the readme, hopefully this will be enough for someone to avoid similar issue.
